packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - sharp

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  eslint-plugin-react@7.37.5: patches/eslint-plugin-react@7.37.5.patch
