/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BestRouteImport } from './routes/best'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandwichSandwichIdRouteImport } from './routes/sandwich.$sandwichId'
import { Route as FamilyChildIdRouteImport } from './routes/family.$childId'
import { Route as SignupParentParentIdRouteImport } from './routes/signup.parent.$parentId'
import { Route as LoginParentParentIdRouteImport } from './routes/login.parent.$parentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BestRoute = BestRouteImport.update({
  id: '/best',
  path: '/best',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandwichSandwichIdRoute = SandwichSandwichIdRouteImport.update({
  id: '/sandwich/$sandwichId',
  path: '/sandwich/$sandwichId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyChildIdRoute = FamilyChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => FamilyRoute,
} as any)
const SignupParentParentIdRoute = SignupParentParentIdRouteImport.update({
  id: '/parent/$parentId',
  path: '/parent/$parentId',
  getParentRoute: () => SignupRoute,
} as any)
const LoginParentParentIdRoute = LoginParentParentIdRouteImport.update({
  id: '/parent/$parentId',
  path: '/parent/$parentId',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/best': typeof BestRoute
  '/cart': typeof CartRoute
  '/create': typeof CreateRoute
  '/family': typeof FamilyRouteWithChildren
  '/latest': typeof LatestRoute
  '/login': typeof LoginRouteWithChildren
  '/menu': typeof MenuRoute
  '/signup': typeof SignupRouteWithChildren
  '/family/$childId': typeof FamilyChildIdRoute
  '/sandwich/$sandwichId': typeof SandwichSandwichIdRoute
  '/login/parent/$parentId': typeof LoginParentParentIdRoute
  '/signup/parent/$parentId': typeof SignupParentParentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/best': typeof BestRoute
  '/cart': typeof CartRoute
  '/create': typeof CreateRoute
  '/family': typeof FamilyRouteWithChildren
  '/latest': typeof LatestRoute
  '/login': typeof LoginRouteWithChildren
  '/menu': typeof MenuRoute
  '/signup': typeof SignupRouteWithChildren
  '/family/$childId': typeof FamilyChildIdRoute
  '/sandwich/$sandwichId': typeof SandwichSandwichIdRoute
  '/login/parent/$parentId': typeof LoginParentParentIdRoute
  '/signup/parent/$parentId': typeof SignupParentParentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/best': typeof BestRoute
  '/cart': typeof CartRoute
  '/create': typeof CreateRoute
  '/family': typeof FamilyRouteWithChildren
  '/latest': typeof LatestRoute
  '/login': typeof LoginRouteWithChildren
  '/menu': typeof MenuRoute
  '/signup': typeof SignupRouteWithChildren
  '/family/$childId': typeof FamilyChildIdRoute
  '/sandwich/$sandwichId': typeof SandwichSandwichIdRoute
  '/login/parent/$parentId': typeof LoginParentParentIdRoute
  '/signup/parent/$parentId': typeof SignupParentParentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/best'
    | '/cart'
    | '/create'
    | '/family'
    | '/latest'
    | '/login'
    | '/menu'
    | '/signup'
    | '/family/$childId'
    | '/sandwich/$sandwichId'
    | '/login/parent/$parentId'
    | '/signup/parent/$parentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/best'
    | '/cart'
    | '/create'
    | '/family'
    | '/latest'
    | '/login'
    | '/menu'
    | '/signup'
    | '/family/$childId'
    | '/sandwich/$sandwichId'
    | '/login/parent/$parentId'
    | '/signup/parent/$parentId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/best'
    | '/cart'
    | '/create'
    | '/family'
    | '/latest'
    | '/login'
    | '/menu'
    | '/signup'
    | '/family/$childId'
    | '/sandwich/$sandwichId'
    | '/login/parent/$parentId'
    | '/signup/parent/$parentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BestRoute: typeof BestRoute
  CartRoute: typeof CartRoute
  CreateRoute: typeof CreateRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRouteWithChildren
  MenuRoute: typeof MenuRoute
  SignupRoute: typeof SignupRouteWithChildren
  SandwichSandwichIdRoute: typeof SandwichSandwichIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best': {
      id: '/best'
      path: '/best'
      fullPath: '/best'
      preLoaderRoute: typeof BestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandwich/$sandwichId': {
      id: '/sandwich/$sandwichId'
      path: '/sandwich/$sandwichId'
      fullPath: '/sandwich/$sandwichId'
      preLoaderRoute: typeof SandwichSandwichIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/$childId': {
      id: '/family/$childId'
      path: '/$childId'
      fullPath: '/family/$childId'
      preLoaderRoute: typeof FamilyChildIdRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/signup/parent/$parentId': {
      id: '/signup/parent/$parentId'
      path: '/parent/$parentId'
      fullPath: '/signup/parent/$parentId'
      preLoaderRoute: typeof SignupParentParentIdRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/parent/$parentId': {
      id: '/login/parent/$parentId'
      path: '/parent/$parentId'
      fullPath: '/login/parent/$parentId'
      preLoaderRoute: typeof LoginParentParentIdRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface FamilyRouteChildren {
  FamilyChildIdRoute: typeof FamilyChildIdRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyChildIdRoute: FamilyChildIdRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface LoginRouteChildren {
  LoginParentParentIdRoute: typeof LoginParentParentIdRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginParentParentIdRoute: LoginParentParentIdRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupParentParentIdRoute: typeof SignupParentParentIdRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupParentParentIdRoute: SignupParentParentIdRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BestRoute: BestRoute,
  CartRoute: CartRoute,
  CreateRoute: CreateRoute,
  FamilyRoute: FamilyRouteWithChildren,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRouteWithChildren,
  MenuRoute: MenuRoute,
  SignupRoute: SignupRouteWithChildren,
  SandwichSandwichIdRoute: SandwichSandwichIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
