export const breadData = [
    {
        shape: "long",
        name: "Ciabatta",
        imageBase: "20200620_101006",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher"],
    },
    {
        shape: "long",
        name: "Semolina",
        imageBase: "20200620_101033",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher"],
    },
    {
        shape: "long",
        name: "Multi-Grain",
        imageBase: "20200620_101059",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher", "halal"],
    },
    {
        shape: "trapezoid",
        name: "Rye",
        imageBase: "20200620_101114",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher"],
    },
    {
        shape: "trapezoid",
        name: "Croissant",
        imageBase: "20200620_101131",
        type: "bread",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        shape: "round",
        name: "Whole Wheat",
        imageBase: "20200620_101224",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher", "halal"],
    },
    {
        shape: "round",
        name: "White",
        imageBase: "20200620_101152",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher", "halal"],
    },
    {
        shape: "long",
        name: "Whole Wheat Wrap",
        imageBase: "20180222_030637",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher", "halal"],
    },
    {
        shape: "long",
        name: "Lettuce Wrap",
        imageBase: "20200620_101255",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher", "halal"],
    },
    {
        shape: "trapezoid",
        name: "Gluten-Free",
        imageBase: "20220202_050837",
        type: "bread",
        dietaryPreferences: ["vegetarian", "vegan", "kosher", "halal"],
    },
];
