export const cheeseData = [
    {
        name: "Swiss",
        imageBase: "20200621_083351_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Provolone",
        imageBase: "20200621_083450_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Mozzarella",
        imageBase: "20200621_083553_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Cheddar",
        imageBase: "20200621_083659_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Pepper Jack",
        imageBase: "20200621_083757_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Muenster",
        imageBase: "20200621_083858_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "American",
        imageBase: "20200621_083946_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Brie",
        imageBase: "20200621_084108_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian"],
    },
    {
        name: "Parmesan",
        imageBase: "20200621_084307_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian"],
    },
    {
        name: "Feta",
        imageBase: "20200621_092955_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "cheese",
        dietaryPreferences: ["vegetarian", "halal"],
    },
];
