export const condimentData = [
    {
        name: "Mayonnaise",
        imageBase: "20200621_115703_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Spicy Mayonnaise",
        imageBase: "20200621_121311_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Spicy Brown Mustard",
        imageBase: "20200621_121727_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Dijon Mustard",
        imageBase: "20200621_121826_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Honey Mustard",
        imageBase: "20200621_121913_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Oil &amp; Vinegar",
        imageBase: "20200621_122357_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Pesto",
        imageBase: "20200621_122152_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Balsamic Dressing",
        imageBase: "20200621_122059_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Russian Dressing",
        imageBase: "20200621_122003_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Horseradish",
        imageBase: "20200621_122556_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "BBQ Sauce",
        imageBase: "20200621_122455_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Ranch",
        imageBase: "20200621_123243_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Sriracha",
        imageBase: "20200621_123445_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Thai Peanut",
        imageBase: "20200621_123357_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Honey",
        imageBase: "20200723_023043_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Hummus",
        imageBase: "20200621_102757_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Peanut Butter",
        imageBase: "20220904_112536_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
    {
        name: "Strawberry Preserves",
        imageBase: "20220904_112727_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
    },
];
