export const condimentData = [
    {
        name: "Mayonnaise",
        imageBase: "20200621_115703_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Spicy Mayonnaise",
        imageBase: "20200621_121311_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Spicy Brown Mustard",
        imageBase: "20200621_121727_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Dijon Mustard",
        imageBase: "20200621_121826_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Honey Mustard",
        imageBase: "20200621_121913_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Oil & Vinegar",
        imageBase: "20200621_122357_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal", "vegan"],
    },
    {
        name: "Pesto",
        imageBase: "20200621_122152_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian"],
    },
    {
        name: "Balsamic Dressing",
        imageBase: "20200621_122059_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Russian Dressing",
        imageBase: "20200621_122003_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["kosher"],
    },
    {
        name: "Horseradish",
        imageBase: "20200621_122556_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "BBQ Sauce",
        imageBase: "20200621_122455_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Ranch",
        imageBase: "20200621_123243_",
        heavy: "_6",
        normal: "_5",
        light: "8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Sriracha",
        imageBase: "20200621_123445",
        heavy: "_6",
        normal: "_5",
        light: "8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Thai Peanut",
        imageBase: "20200621_123357",
        heavy: "_6",
        normal: "_5",
        light: "8",
        type: "condiment",
        dietaryPreferences: ["vegetarian"],
    },
    {
        name: "Honey",
        imageBase: "20200723_023043",
        heavy: "_6",
        normal: "_5",
        light: "8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher"],
    },
    {
        name: "Hummus",
        imageBase: "20200621_102757",
        heavy: "_6",
        normal: "_5",
        light: "8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal", "vegan"],
    },
    {
        name: "Peanut Butter",
        imageBase: "20220904_112536",
        heavy: "_6",
        normal: "_5",
        light: "8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
    {
        name: "Strawberry Preserves",
        imageBase: "20220904_112727",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "condiment",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
];
