export const proteinData = [
    {
        name: "Turkey",
        imageBase: "20200621_081721_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["halal", "kosher"],
    },
    {
        name: "Roast Beef",
        imageBase: "20200621_082049_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["kosher", "halal"],
    },
    {
        name: "Ham",
        imageBase: "20200621_081904_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Prosciutto",
        imageBase: "20200621_082227_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Corned Beef",
        imageBase: "20200621_082443_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["kosher", "halal"],
    },
    {
        name: "Pastrami",
        imageBase: "20200621_082538_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["kosher", "halal"],
    },
    {
        name: "Genoa Salami",
        imageBase: "20200621_082005_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Soppressata",
        imageBase: "20200813_113834_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Capocollo",
        imageBase: "20200909_100415_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Pepperoni",
        imageBase: "20200621_082346_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Baked Chicken",
        imageBase: "20200621_082626_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["halal", "kosher"],
    },
    {
        name: "Bacon",
        imageBase: "20200621_082719_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: [],
    },
    {
        name: "Chicken Salad",
        imageBase: "20200621_082821_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["halal", "kosher"],
    },
    {
        name: "Tuna Salad",
        imageBase: "20200621_082909_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["kosher", "halal"],
    },
    {
        name: "Egg Salad",
        imageBase: "20200621_082959_",
        half: "_7",
        full: "_1",
        double: "_2",
        type: "protein",
        dietaryPreferences: ["vegetarian", "kosher", "halal"],
    },
];
