export const toppingData = [
    {
        name: "Tomatoes",
        imageBase: "20200621_093051_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Lettuce",
        imageBase: "20200621_093526_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Onions",
        imageBase: "20200621_095313_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Arugula",
        imageBase: "20200621_095441_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Spinach",
        imageBase: "20200621_095524_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Kale",
        imageBase: "20200621_095607_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Alfalfa Sprouts",
        imageBase: "20200621_095722_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Cucumbers",
        imageBase: "20200621_095400_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Pickles",
        imageBase: "20200621_095938_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Olives",
        imageBase: "20200621_100026_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Banana Peppers",
        imageBase: "20200621_100115_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Jalapenos",
        imageBase: "20200621_100218_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Roasted Red Peppers",
        imageBase: "20200621_100648_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Sliced Apple",
        imageBase: "20200621_100309_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Coleslaw",
        imageBase: "20200621_100450_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Sauerkraut",
        imageBase: "20200621_100559_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Kettle Cooked Chips",
        imageBase: "20200621_100356_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
    {
        name: "Avocado",
        imageBase: "20200621_100736_",
        heavy: "_6",
        normal: "_5",
        light: "_8",
        type: "topping",
    },
];
